steps:
- name: 'python:3.10'
  entrypoint: 'pip'
  args: ['install', '-r', 'requirements.txt', '--user']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy']
options:
  logging: CLOUD_LOGGING_ONLY